
package project;

import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;

public class Uretici extends javax.swing.JFrame {
    Tedarikci td=new Tedarikci();
    int i=0,a=0,b=0,c=0;
    ArrayList<String> sehir_id = new ArrayList<String>();
    ArrayList<String> sehir_adi = new ArrayList<String>();
    ArrayList<Integer> mesafe = new ArrayList<Integer>();
    ArrayList<String> yurt_ic_dis = new ArrayList<String>();
    ArrayList<String> sirket_maliyet_firma = new ArrayList<String>();
    ArrayList<Integer> butun_sirket_maliyet = new ArrayList<Integer>();
    ArrayList<Integer> sirket_maliyet = new ArrayList<Integer>();

    

   
    public Uretici() {
        initComponents();
        try{
            Connection myConn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/project?verifyServerCertificate=false&useSSL=true","root","1234");
            Statement myStat =(Statement) myConn.createStatement();
            ResultSet myRs=myStat.executeQuery("select * from sehir");
             while(myRs.next()){
                 sehir_id.add(myRs.getString("sehir_id"));
                 sehir_adi.add(myRs.getString("sehir_adi"));
                 mesafe.add(myRs.getInt("mesafe"));
                 yurt_ic_dis.add(myRs.getString("yurt_ic_dis"));
                 i++;
              
             }
             a=i;
             i=0;
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "firma_adi", "sehir", "aldigi_hammadde", "alis_maliyeti", "stok", "urun_adi", "urun_bilesenleri"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("hammadde");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Satın Al");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("hammadde_miktari");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(jTextField3))
                                .addGap(26, 26, 26)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(61, 61, 61)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int en_dusuk_maliyet=0,miktar=0,sayac_1=0,sayac_2=0;
        b=a;
        c=td.i;
          while(a!=0){
                 System.out.println(sehir_id.get(b-a)+" "+sehir_adi.get(b-a)+" "+mesafe.get(b-a)+" "+yurt_ic_dis.get(b-a));
                 sayac_1++;
                 a--;
          }
          
          while(c!=0){
              if(td.hammadde.get(td.i-c).equalsIgnoreCase(jTextField1.getText())){
                System.out.println(td.firma_adi.get(td.i-c)+" "+td.satis_fiyati.get(td.i-c));
                
                butun_sirket_maliyet.add(td.satis_fiyati.get(td.i-c));
                sayac_2++;
              
              }
              c--;
          }
          
          
          miktar=Integer.parseInt(jTextField3.getText());
          System.out.println(miktar);
          
          for (int j = 0; j < sayac_2; j++) {
              if(td.hammadde.get(sayac_2).equalsIgnoreCase(jTextField1.getText())){
              for (int k = 0; k < sayac_1; k++) {
                if(td.firma_konum.get(j).equalsIgnoreCase(sehir_adi.get(k))){
                    if(yurt_ic_dis.get(k).equalsIgnoreCase("yurtici")){
                        sirket_maliyet_firma.add(td.firma_adi.get(k));
                        sirket_maliyet.add((mesafe.get(k)/2)+(miktar*butun_sirket_maliyet.get(j)));
                   }else if (yurt_ic_dis.get(k).equalsIgnoreCase("yurtdisi")) {
                        sirket_maliyet_firma.add(td.firma_adi.get(k));
                        sirket_maliyet.add(mesafe.get(k)+(miktar*butun_sirket_maliyet.get(j)));                    }
                   }  
              }
          }
          }
          
          
          
          for (int j = 0; j < sirket_maliyet_firma.size(); j++) {
              System.out.println(sirket_maliyet_firma.get(j)+"  "+sirket_maliyet.get(j));
        }
          
          int m=0;
            en_dusuk_maliyet=sirket_maliyet.get(0);
          for (int j = 1; j < sirket_maliyet.size(); j++) {
              System.out.println(sirket_maliyet.get(j));
            if(en_dusuk_maliyet>sirket_maliyet.get(j)){
                en_dusuk_maliyet=sirket_maliyet.get(j);
                m=j;
          }
        }
          try{
        String sorgu=String.format("update tedarikci set hammadde_miktari='%d' where firma_id=%s ",Integer.parseInt(td.hammadde_miktari.get(m))-miktar,m) ;
        int gunc=td.myStat.executeUpdate(sorgu);
          }catch(Exception e){
              e.printStackTrace();
          }
          
          System.out.println("En düşük maliyet= "+en_dusuk_maliyet);
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uretici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uretici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uretici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uretici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uretici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
